language: generic 
sudo: required
services:
  - docker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-648972008149
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY