language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t youngsingtan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true youngsingtan/react-test npm test

after_success:
  - docker build -t youngsingtan/multi-client ./client
  - docker build -t youngsingtan/multi-nginx ./nginx
  - docker build -t youngsingtan/multi-server ./server
  - docker build -t youngsingtan/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push youngsingtan/multi-client
  - docker push youngsingtan/multi-nginx
  - docker push youngsingtan/multi-server
  - docker push youngsingtan/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: southeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-1-648972008149
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY